# Generated by Django 4.1.4 on 2022-12-26 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0002_alter_comment_text"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="dislikes",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="likes",
        ),
    ]
