# Generated by Django 4.1.5 on 2023-01-02 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0003_remove_comment_dislikes_remove_comment_likes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="text",
            field=models.CharField(max_length=250),
        ),
    ]
