# Generated by Django 4.1.5 on 2023-01-02 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0004_alter_comment_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="dislikes",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="comment",
            name="likes",
            field=models.IntegerField(null=True),
        ),
    ]
